'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label={WAITING_HUMAN:'Waiting for human',RUNNING:'Agent working',WAITING_PERMISSION:'Permission blocked',WAITING_CAPACITY:'Capacity paused',COMPLETED:'Completed'};
let state,selected='GOV-027',filter='all',motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;
async function api(path,body){const o=body?{method:'POST',headers:{'Content-Type':'application/json','X-Court-Token':state?.csrf||''},body:JSON.stringify(body)}:{};const r=await fetch(path,o),j=await r.json();if(!r.ok)throw Error(j.error||`Request failed ${r.status}`);return j}
const task=()=>state.tasks.find(t=>t.id===selected)||state.tasks[0];
const age=ts=>{const m=Math.max(0,Math.floor((Date.now()/1000-ts)/60));return m>59?`${Math.floor(m/60)}h ${m%60}m`:`${m}m`};
const badge=s=>`<span class="status ${esc(s)}">${esc(label[s]||s)}</span>`;
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)}
function curve(a,b){const x=state.nodes.find(n=>n.id===a),y=state.nodes.find(n=>n.id===b);if(!x||!y)return'';const m=(x.x+y.x)/2;return`M ${x.x} ${x.y} C ${m} ${x.y}, ${m} ${y.y}, ${y.x} ${y.y}`}
function graph(){const t=task(),route=new Set(t.route);$('#graph').innerHTML=`<svg viewBox="0 0 1140 500" aria-label="Ownership topology"><defs><filter id="glow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>${state.edges.map(([a,b])=>`<path class="edge ${route.has(a)&&route.has(b)?'route':''}" d="${curve(a,b)}"/>`).join('')}${state.nodes.map(n=>{const own=n.id===t.node,c=state.tasks.filter(x=>x.node===n.id&&x.status!=='COMPLETED').length;return`<g class="graph-node ${own?'selected':''}" data-node="${n.id}" tabindex="0" transform="translate(${n.x},${n.y})">${own?'<circle class="halo" r="45"/>':''}<circle class="node" r="29"/><text class="symbol" text-anchor="middle" y="6">${n.symbol}</text><text class="nt" text-anchor="middle" y="57">${esc(n.title)}</text><text class="ns" text-anchor="middle" y="76">${esc(n.role)}</text>${c?`<circle class="count" cx="23" cy="-22" r="10"/><text class="ct" x="23" y="-18" text-anchor="middle">${c}</text>`:''}</g>`}).join('')}</svg>`;$('#graph-stamp').textContent=`${t.id} · v${t.version} · synthetic`}
function owner(){const t=task();$('#owner-panel').innerHTML=`<div class="owner-label">BALL IN COURT <span>${age(t.age_start)} IN STATE</span></div><div class="owner-person"><span class="owner-avatar">${t.owner==='Paul'?'P':'◇'}</span><div><h2>${esc(t.owner)}</h2><small>Current action owner</small></div></div><div class="task-id">${t.id} / ${esc(t.project)}</div><h3>${esc(t.title)}</h3>${badge(t.status)}<div class="next-action"><span>THE NEXT MOVE</span><p>${esc(t.next_action)}</p></div><p class="reason">${esc(t.reason)}</p><div class="links"><button data-artifact="${t.plan}">Plan ↗</button><button data-artifact="${t.code}">Code ↗</button><a href="#/feature/${t.feature}">Feature ↗</a></div><button class="primary" id="advance" ${state.paused||t.status==='COMPLETED'?'disabled':''}>Simulate accepted handoff →</button>`}
function stats(){const a=state.tasks.filter(t=>t.status!=='COMPLETED');const v=[['In your court',a.filter(t=>t.owner==='Paul').length],['Agent-owned',a.filter(t=>['librarian','pipeline','governance','critic'].includes(t.node)).length],['Permission blocked',a.filter(t=>t.status==='WAITING_PERMISSION').length],['Capacity paused',a.filter(t=>t.status==='WAITING_CAPACITY').length]];$('#stats').innerHTML=v.map(([k,n])=>`<div class="stat"><span>${k}</span><b>${String(n).padStart(2,'0')}</b></div>`).join('')}
function mini(){const rows=state.tasks.map(t=>`<button class="mini-row ${t.id===selected?'selected':''}" data-task="${t.id}"><span class="task-id">${t.id}</span><span><b>${esc(t.title)}</b><small>${esc(t.owner)} · ${age(t.age_start)}</small></span>${badge(t.status)}</button>`).join('');$('#mini-queue').innerHTML=rows}
function activity(){$('#activity').innerHTML=state.events.slice(0,4).map(e=>`<div class="activity-item"><b>${esc(e.task?`${e.task} → ${e.owner}`:e.kind)}</b><small>${esc(e.note||'Recorded local event')}</small></div>`).join('')||'<div class="empty">No handoffs recorded. Idle means idle.</div>'}
function queue(){let x=state.tasks;if(filter==='mine')x=x.filter(t=>t.owner==='Paul');if(filter==='agents')x=x.filter(t=>['librarian','pipeline','governance','critic'].includes(t.node));if(filter==='blocked')x=x.filter(t=>['WAITING_PERMISSION','WAITING_CAPACITY','BLOCKED'].includes(t.status));$('#queue-full').innerHTML=x.map(t=>`<article class="full-task"><div><span class="task-id">${t.id}</span><h3>${esc(t.title)}</h3><p><strong>Next:</strong> ${esc(t.next_action)}</p><p>${esc(t.reason)}</p><div class="links"><button data-task="${t.id}" data-return="court">View court</button><button data-artifact="${t.plan}">Plan</button><button data-artifact="${t.code}">Code</button></div></div><div>${badge(t.status)}<small>${esc(t.owner)}<br>Accountable: ${esc(t.accountable)}</small></div></article>`).join('')||'<div class="empty">No tasks in this view.</div>';$$('#filters button').forEach(b=>b.classList.toggle('selected',b.dataset.filter===filter))}
function features(){const id=location.hash.split('/')[2];$('#feature-grid').innerHTML=state.features.map(f=>`<article class="panel feature-card"><div class="feature-icon">⬡</div><span class="tiny">${esc(f.status).toUpperCase()}</span><h2>${esc(f.title)}</h2><p>${esc(f.subtitle)}</p><div class="links"><button data-artifact="${f.plan}">Plan ↗</button><button data-artifact="${f.code}">Code ↗</button><a href="#/feature/${f.id}">Inspect ↗</a></div></article>`).join('');const f=state.features.find(x=>x.id===id);$('#feature-detail').innerHTML=f?`<section class="panel feature-detail"><span class="eyebrow">FEATURE CONTRACT</span><h2>${esc(f.title)}</h2><div class="checks">${f.checks.map(c=>`<span>◇ ${esc(c)}</span>`).join('')}</div><button data-task="${f.task}" data-return="court">Trace ownership →</button></section>`:''}
function budget(){const c=state.config;$('#budget-content').innerHTML=`<div class="budget-grid"><section class="panel budget-card"><span class="eyebrow">COST CONTROL BEFORE AUTONOMY</span><h2>Your seat is not a blank check.</h2><div class="unknown">UNKNOWN</div><p>Work-seat billing mode is unverified here. Execution stays off. Remaining quota is never fabricated.</p><div class="budget-row"><span>Prototype Claude calls</span><b>${state.dispatches}</b></div><div class="budget-row"><span>Automatic API fallback</span><b>Forbidden</b></div><button data-artifact="budget">Read budget policy ↗</button></section><section class="panel budget-card"><span class="eyebrow">CONSERVATIVE PILOT</span><h2>Sleep until useful.</h2>${[['Concurrency',c.max_concurrency],['Dispatches/day',c.max_dispatches_per_day],['Turns/dispatch',c.max_turns_per_dispatch],['Wall time',c.max_wall_seconds+'s'],['Batch window',c.batch_window_seconds/60+' min']].map(([a,b])=>`<div class="budget-row"><span>${a}</span><b>${b}</b></div>`).join('')}<button data-artifact="runtime">Open configuration ↗</button></section></div>`}
function render(){stats();graph();owner();mini();activity();queue();features();budget();$('#call-count').textContent=state.dispatches;$('#nav-count').textContent=String(state.tasks.length).padStart(2,'0');$('#pause').textContent=state.paused?'▶ Resume demo':'Ⅱ Pause demo';document.body.classList.toggle('reduced-motion',!motion)}
function route(){let p=(location.hash||'#/court').split('/')[1];if(p==='feature')p='features';if(!['court','queue','memory','features','budget'].includes(p))p='court';$$('.view').forEach(v=>v.hidden=v.id!==`view-${p}`);$$('nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===p));const t={court:['Know who moves next.','Every task has an owner. Every decision has evidence.'],queue:['The next move, made explicit.','See ownership and blockers without ambiguity.'],memory:['Context without the cloud bill.','Search approved local sources and open exact evidence.'],features:['From task to working feature.','Trace features to plans, code and current owners.'],budget:['Autonomy with a hard stop.','Budget and egress gates come before unattended inference.']};$('#page-title').textContent=t[p][0];$('#page-subtitle').textContent=t[p][1];if(p==='features')features()}
async function artifact(id,line){try{const a=await api('/api/artifact?id='+encodeURIComponent(id));$('#artifact-title').textContent=a.title;$('#artifact-path').textContent=a.path;$('#artifact-kind').textContent=(a.kind||'source').toUpperCase();$('#source-meta').textContent='SHA-256 '+a.sha256;$('#source-lines').innerHTML=a.text.split('\n').map((x,i)=>`<div class="source-line ${line&&i+1===+line?'highlight':''}"><span>${i+1}</span><code>${esc(x)}</code></div>`).join('');$('#artifact-dialog').showModal()}catch(e){toast(e.message)}}
async function search(q){$('#query').value=q;try{const r=await api('/api/search?q='+encodeURIComponent(q));$('#search-info').textContent=`${r.results.length} results · ${r.backend} · no Claude calls`;$('#search-results').innerHTML=r.results.map(x=>`<article class="search-result"><h3>${esc(x.title)}</h3><small>${esc(x.path)} · L${x.start}-${x.end}</small><pre>${esc(x.text)}</pre><button data-artifact="${x.artifact}" data-line="${x.start}">Open exact source ↗</button></article>`).join('')||'<div class="empty">No matching approved source.</div>'}catch(e){toast(e.message)}}
function packet(a,b){if(!motion||document.hidden)return;const s=$('#graph svg');if(!s)return;const n='http://www.w3.org/2000/svg',c=document.createElementNS(n,'circle'),m=document.createElementNS(n,'animateMotion');c.setAttribute('r','6');c.setAttribute('class','packet');m.setAttribute('dur','1.4s');m.setAttribute('path',curve(a,b));m.setAttribute('fill','freeze');c.append(m);s.append(c);m.beginElement();setTimeout(()=>c.remove(),1600)}
document.addEventListener('click',async e=>{const x=e.target.closest('[data-artifact],[data-task],[data-node],[data-query],[data-filter]');if(x){if(x.dataset.artifact){e.preventDefault();artifact(x.dataset.artifact,x.dataset.line)}else if(x.dataset.task){selected=x.dataset.task;render();if(x.dataset.return)location.hash='#/court'}else if(x.dataset.node){const t=state.tasks.find(t=>t.node===x.dataset.node&&t.status!=='COMPLETED');if(t){selected=t.id;render()}}else if(x.dataset.query)search(x.dataset.query);else if(x.dataset.filter){filter=x.dataset.filter;queue()}}if(e.target.closest('#advance')){const t=task(),from=t.node;try{state=await api('/api/advance',{task:t.id,version:t.version});render();packet(from,task().node);toast('Demo handoff recorded. No work system changed.')}catch(err){toast(err.message)}}});
$('#motion').onclick=()=>{motion=!motion;render();$('#motion').textContent=motion?'◌ Motion on':'◌ Motion off'};
$('#pause').onclick=async()=>{try{state=await api('/api/pause',{paused:!state.paused});render()}catch(e){toast(e.message)}};
$('#close-dialog').onclick=()=>$('#artifact-dialog').close();
$('#search-form').onsubmit=e=>{e.preventDefault();search($('#query').value)};
window.addEventListener('hashchange',route);
(async()=>{try{state=await api('/api/state');render();route()}catch(e){$('#main').innerHTML=`<section class="panel budget-card"><h2>Local service unavailable</h2><p>${esc(e.message)}</p><p>Run <code>python -m src.server</code> from the repository root.</p></section>`}})();
